<?php 
$this->title = "View All Accounts";
$this->headTitle($this->title);
?>

<table width='300' border='1' >
<?php  if($this->resultList){ ?>
<tr align="center">
	<th>Member Name</th>
	<th>Date Joined</th>
</tr>
<?php 
    $lineNr = 0;
    foreach ($this->resultList as $result){
?>
<tr align="center" bgcolor="<?php echo (($lineNr % 2) ? '' : 'lavender')?>" >
	<td><a href="<?php echo urlencode($result['username'])?>" >
	<?php echo $result['username']?>
	</a></td>
	<td><?php echo $result['created_date']?></td>
</tr>
<?php 
        $lineNr ++;
    }
    
?>
    <tr><td colspan='2'>Total Nr: <?php print_r( $this->totalMemberNr) ?></td></tr>
<?php 
}else { 
?>
<tr>
	<td>There are no active members now in sys.</td>
</tr>
<?php } ?>
	
</table>
