	<link type="text/css" rel="stylesheet" href="/asset/css/style.css" />	
	<div class='body_header'>
	<div class='nav' id='logo'><a href='/' ><img src="http://sunnyboy.me/photo/_.jpg" /></a></div>
            <?php 
            if(isset($_SESSION['username'])){
                ?>
                <div class='nav' id='account_manager'><a href="/account/manager">@
                <?php 
                echo $_SESSION['username'];
                ?>
                </a></div> <div class='nav' id='account_logout'><a href='/account/logout'>Log out</a></div>
                <?php 
            }else {
            ?>
            	<div class='nav' id='account_login'><a href='/account/login' >Log in</a></div> <div class='nav' id='account_new'><a href='/account/new' >Sign up</a></div> 
                <?php 
            }?>
            <div class='nav' id='restaurant_list-all-restaurants'><a href='/restaurant/list-all-restaurants'>All Rests</a></div> 
            <?php if(isset($_SESSION['id']) && ($_SESSION['status'] == 'admin') ){ ?>
            <div class='nav' id='restaurant_list-all-restaurants'><a href='/restaurant/new'>Add Rest</a></div> 
            <?php } ?>
	</div>
<br /><br />
