<table width="100%" cellpadding="0" cellspacing="0">
    <tr bgcolor="#eeeeee"><td><h1>Sunny Rest</h1></td></tr>
    <tr>
    	<td>
            <?php 
            if(isset($_SESSION['username'])){
                ?>
                <a href="/account/manager">
                <?php 
                echo $_SESSION['username'];
                ?>
                </a> | <a href='/account/logout'>Log out</a> | 
                <?php 
            }else {
            ?>
            	<a href='/account/login' >Log in</a> | <a href='/account/new' >Sign up</a> | 
                <?php 
            }?>
            <a href='/restaurant/list-all-restaurants'>View All Restaurants</a> | 
            <?php if(isset($_SESSION['id']) && ($_SESSION['status'] == 'admin') ){ ?>
            <a href='/restaurant/new'>Add Restaurants</a> | 
            <?php }?>
            <!-- My Store</td></tr> -->
</table>
<br /><br />
