<?php 
$this->title = "View All Restaurants";
$this->headTitle($this->title);
?>

<table>
    <tr>
        <th>Name</th>
        <th>Savour</th>
        <th>Detail</th>
        <?php if(false){ ?><th>Book Seats</th><?php } ?>
    </tr>

    <?php 
    $lineNr = 0;
    foreach ($this->resultList as $result){
    ?>
    <tr bgcolor='<?php echo ($lineNr % 2) ? "": "lavender" ?>'>
    	<td><?php echo $result['restaurant_name']?></td>
    	<td><?php echo $result['savour']?></td>
    	<td><a href='profile?id=<?php echo $result['id'] ?>'>View</a></td>
    	<?php if(false){ ?>
    	<td><a href='book?id=<?php echo $result['id'] ?>'>Book Now!</a></td>
    	<?php } ?>
    </tr>
    <?php 
        $lineNr++;
    }
    ?>
</table>
