<?php 
//require_once 'library/Sunny/Scripts/sunny_function.php';
?>
<?php 
$result = $this->result;
$restName = $result['restaurant_name'];
$this->title = "$restName";
$this->headTitle($this->title);
?>
<?php $currentUrl = ((!empty($_SERVER['HTTPS'])) ? "https://" : "http://").$_SERVER['SERVER_NAME'].(($_SERVER["SERVER_PORT"] == "80")?"":(":".$_SERVER["SERVER_PORT"])).$_SERVER['REQUEST_URI']; ?>


<br /><div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<fb:like href="<?php echo $currentUrl ?>" send="true" layout="button_count" width="450" show_faces="false"></fb:like><br />
<br />

<!-- facebook html5 version
<div class="fb-like" data-href="<?php echo $currentUrl ?>" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false"></div>
<br />
 -->

<script src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
<br />


<b>
	Savour: <?php echo $result['savour']?><br>
	Email: <?php echo $result['email']?><br>
	<a href='book?id=<?php echo $result['id'] ?>'>Book Seats Now!</a>
</b>
